version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379" # Map host port 6380 to container port 6379
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://default:H34edGsibL58PjUCXMS63ZlC7EHcoQFb@redis-14388.c82.us-east-1-2.ec2.redns.redis-cloud.com:14388
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/workers/worker.js
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://default:H34edGsibL58PjUCXMS63ZlC7EHcoQFb@redis-14388.c82.us-east-1-2.ec2.redns.redis-cloud.com:14388
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge